/**
 * One-time backfill: assigns one-word relType labels to edges in maps that
 * were generated by the question-guided pipeline (which previously left
 * relType empty). Targets "Google Xi Test7" by default; pass a map title
 * as the first argument to target a different map.
 *
 * Usage:
 *   node --env-file=.env.local --import tsx scripts/backfill-rel-types.ts
 *   node --env-file=.env.local --import tsx scripts/backfill-rel-types.ts "Google Xi Test7"
 */

import { generateText } from "ai";
import { anthropic } from "@ai-sdk/anthropic";
import { createClient } from "@supabase/supabase-js";

const TARGET_TITLE = process.argv[2] ?? "Google Xi Test7";

const PALETTE = [
  "Supports", "Contests", "Qualifies", "Reframes",
  "Extends", "Grounds", "Implies", "Illustrates",
];

const supabase = createClient(
  process.env.NEXT_PUBLIC_SUPABASE_URL!,
  process.env.SUPABASE_SERVICE_ROLE_KEY!,
);

async function classifyLabels(
  edges: { id: string; label: string }[],
): Promise<Record<string, string>> {
  const prompt = `You are classifying argument map edge labels into a one-word vocabulary.

PALETTE: ${PALETTE.join(" | ")}

If none fit, coin a short hyphenated word (e.g. "Narrows"). Never use pro/con / for/against.

For each edge below, return the single best palette word for its label.

EDGES:
${edges.map((e) => `  ${e.id}: "${e.label}"`).join("\n")}

Return ONLY a JSON object mapping edge id to one-word type, e.g.:
{"e1":"Contests","e2":"Implies"}`;

  const { text } = await generateText({
    model: anthropic("claude-sonnet-4-6"),
    prompt,
  });

  const match = text.match(/\{[\s\S]*\}/);
  if (!match) throw new Error(`No JSON in response: ${text}`);
  return JSON.parse(match[0]) as Record<string, string>;
}

async function main() {
  console.log(`Fetching map: "${TARGET_TITLE}"…`);
  const { data, error } = await supabase
    .from("Dialectica_maps")
    .select("id, title, data")
    .eq("title", TARGET_TITLE)
    .maybeSingle();

  if (error) throw error;
  if (!data) throw new Error(`Map not found: "${TARGET_TITLE}"`);

  console.log(`Found map ${data.id}`);

  // Collect all edges missing relType across all frames
  const mapData = data.data as {
    frames: Record<string, { edges: { id: string; relType?: string; label?: string }[] }>;
  };

  const toClassify: { frameId: string; edgeIdx: number; id: string; label: string }[] = [];
  for (const [frameId, frame] of Object.entries(mapData.frames ?? {})) {
    for (let i = 0; i < (frame.edges ?? []).length; i++) {
      const edge = frame.edges[i];
      if (!edge.relType && edge.label) {
        toClassify.push({ frameId, edgeIdx: i, id: edge.id, label: edge.label });
      }
    }
  }

  if (toClassify.length === 0) {
    console.log("No edges need backfilling — all relType fields are already set.");
    return;
  }

  console.log(`Classifying ${toClassify.length} edges…`);
  const classified = await classifyLabels(
    toClassify.map((e) => ({ id: e.id, label: e.label })),
  );

  // Apply classifications back into the map data
  for (const { frameId, edgeIdx, id } of toClassify) {
    const relType = classified[id];
    if (relType) {
      mapData.frames[frameId].edges[edgeIdx].relType = relType;
      console.log(`  ${id}: "${toClassify.find(e => e.id === id)?.label}" → ${relType}`);
    } else {
      console.warn(`  ${id}: no classification returned`);
    }
  }

  // Write back to Supabase
  const { error: updateError } = await supabase
    .from("Dialectica_maps")
    .update({ data: mapData })
    .eq("id", data.id);

  if (updateError) throw updateError;
  console.log(`\nDone — updated ${data.id} in Supabase.`);
}

main().catch((err) => { console.error(err); process.exit(1); });
